/* Generated by Yosys 0.9+4008 (git sha1 1af99480, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.1-10.10" *)
module good_mux(i0, i1, sel, y);
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.24-2.26" *)
  wire _0_;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.35-2.37" *)
  wire _1_;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.46-2.49" *)
  wire _2_;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.63-2.64" *)
  wire _3_;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.24-2.26" *)
  input i0;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.35-2.37" *)
  input i1;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.46-2.49" *)
  input sel;
  (* src = "/home/spdy18695/vlsi/sky130RTLDesignAndSynthesisWorkshop/verilog_files/good_mux.v:2.63-2.64" *)
  output y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = sel;
  assign y = _3_;
endmodule
